SET IDENTITY_INSERT [dbo].[AddQuestions] ON
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (4, 1, N'HTML stands for?', N'MCQ', N'Hyper Text Markup Language', N'High Text Markup Language', N'Hyper Tabular Markup Language', N'None of these', N'Hypertext Markup Language is the standard markup language for creating web pages and web applications. With Cascading Style Sheets and JavaScript, it forms a triad of cornerstone technologies for the World Wide Web.', 1, N'OptionA')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (5, 1, N'which of the following tag is used to mark a begining of paragraph ', N'MCQ', N'< TD >', N'< br >', N'< P >', N'< TR >', N'Paragraph Tag < p >< / p >', 1, N'OptionC')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (6, 1, N'In HTML we use _____ tag to defines quotation marks around the text ?', N'BLANK', NULL, NULL, NULL, NULL, N'< q > tag is used for quotes.', 1, N'< q >')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (7, 1, N'In HTML we use _____ tag to defines superscripted text?', N'BLANK', NULL, NULL, NULL, NULL, N'< sup > is used for superscripted text', 1, N'< sup >')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (8, 1, N'From which tag descriptive list starts ?', N'MCQ', N'< LL >', N'< DD >', N'< DL >
', N'< DS >', N'A description list, with terms and descriptions: < dl > < dt >Coffee< / dt > < dd >Black hot drink< / dd > < dt >Milk< / dt > < dd >White cold drink< / dd > < / dl >.', 1, N'OptionC')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (9, 1, N'Correct HTML tag for the largest heading is', N'MCQ', N'< head >', N'< h6 >', N'< heading >', N'< h1 >', N'The h1 element is used to indicate the most important (or highest-level) heading on the page. In total, we have six heading levels to choose from—h1 to h6—to add structure to the web page. h1 is the highest heading level ( and, by default, the largest in terms of font size ) and h6 the lowest ( and smallest ).', 1, N'OptionD')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (10, 1, N'In HTML we use _____ tag to defines highlighted text ?', N'BLANK', NULL, NULL, NULL, NULL, N'The <mark> tag was introduced in HTML 5. The HTML <mark> tag is used for indicating text as marked or highlighted for reference purposes, due to its relevance in another context. The < mark > tag is supported in all major browsers. Use the < mark > tag if you want to highlight parts of your text.', 1, N'< mark >')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (11, 1, N'In HTML we use _____ tag to defines small text ?', N'BLANK', NULL, NULL, NULL, NULL, N'The HTML <small> element is found within the <body> tag. The <small> tag is used to make the text one size smaller (ie: from x-large to large, large to medium, medium to small). The < small > tag can not make the text smaller than the browser''s minimum font size.', 1, N'< small >')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (12, 1, N'A much better approach to establish the base URL is to use', N'MCQ', N'BASE element', N'HEAD element', N'both (a) and (b)', N'none of these', N'The HTML < base > tag is used in defining the base URI or URL for all the relative links in the HTML document.', 1, N'OptionA')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (13, 1, N'The tag used to create a new list item and also include a hyperlink is', N'MCQ', N'< LI >', N'< DL >', N'< DD >', N'< UL >', N'Definition and Usage. The <li> tag defines a list item. The < li > tag is used in ordered lists(< ol >), unordered lists (< ul >), and in menu lists (< menu >).', 1, N'OptionA')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (14, 1, N'In HTML we use _____ tag to get text in Italic?', N'BLANK', NULL, NULL, NULL, NULL, N'The < i > tag defines a part of text in an alternate voice or mood. The content of the <i> tag is usually displayed in italic. The <i> tag can be used to indicate a technical term, a phrase from another language, a thought, or a ship name, etc.', 1, N'< i >')
INSERT INTO [dbo].[AddQuestions] ([Questionid], [QLevel], [Question], [Type], [OptionA], [OptionB], [OptionC], [OptionD], [Explaination], [Marks], [Answer]) VALUES (15, 1, N'In HTML we use _____ tag to get Bold Text ?', N'BLANK', NULL, NULL, NULL, NULL, N'In the previous chapter, you learned about the HTML style attribute. HTML also defines special elements for defining text with a special meaning. HTML uses elements like <b> and <i> for formatting output, like bold or italic text. Formatting elements were designed to display special types of text: < b > - Bold text.', 1, N'< bold >')
SET IDENTITY_INSERT [dbo].[AddQuestions] OFF
